#!/bin/sh

#################################################################
#   Copyright (c) 2020 lencx, Licensed MIT license              #
#   Quickly create a template file by command                   #
#   author: lencx <cxin1314@gmail.com>                          #
#   create_at: Aug 07, 2020                                     #
#################################################################

CREATE_AT=$(LANG=en_us_88591; date '+%b %d, %Y')
AUTHOR='lencx'
PKG_NAME='new'
PKG_VERSION='0.1.0'
ROOT_DIR=src
TARGET_DIR=''
DIR_NAME=''
FILE_NAME='main'
FILE_TYPE='js'
FILE_CONTENTS=''
IS_DONE="false"
NAME_1='' # aa_bb_cc => AaBbCc
NAME_2='' # aa_bb_cc => aaBbCc

COLOR_RED="\033[0;31m"
COLOR_GREEN="\033[0;32m"
COLOR_YELLOW="\033[0;33m"
COLOR_BLUE="\033[0;34m"
COLOR_RESET="\033[0m"

INFO_WARN="${COLOR_YELLOW}[WARN]"
INFO_EXISTS="${COLOR_BLUE}[EXIST]"
INFO_OK="${COLOR_GREEN}[OK]"

main() {
  if [ ! $1 ];then
    handle_args "-h"
    exit 0
  fi

  echo ""
  if [ $IS_DONE == "true" ];then echo "✨Done!\n"; fi
  echo "$ cd $TARGET_DIR"
}

handle_args() {
  while test $# -gt 0; do
    case $1 in
      -h|--help)
        echo "Quickly create a template file by command"
        echo ""
        echo "Usage: $PKG_NAME [options] directory_name"
        echo "Version: $PKG_VERSION"
        echo ""
        echo "Options:"
        echo "-a, --author          files creator"
        echo "-h, --help            print '$PKG_NAME' command line options"
        echo "-l, --lang            programming language(file extension), default: js"
        echo "                      example: -l=rs, -l=go etc."
        echo "-v, --version         print '$PKG_NAME' version"
        exit 0
      ;;

      -a*|--author*)
        export NAME=`echo $1 | sed -e 's/^[^=]*=//g'`
        AUTHOR=$NAME
        shift
      ;;

      -l*|--lang*)
        export LANG_TYPE=`echo $1 | sed -e 's/^[^=]*=//g'`
        FILE_TYPE=$LANG_TYPE
        shift
      ;;

      -v|--version)
        echo "$PKG_NAME $PKG_VERSION"
        exit 0
      ;;

      *)
        TARGET_DIR=$ROOT_DIR/$1
        DIR_NAME=$1
        NAME_1=$(camel_case "$1" "false")
        NAME_2=$(camel_case "$1" "true")
        break
      ;;
    esac
  done

  if [ ! $1 ];then file_missing $1;fi

  mkdir -p $TARGET_DIR
  echo ""
  create_file "README.md" "# `echo $1 | sed 's/_/ /g'`\n"
  create_file_type "$FILE_TYPE" "$1"
}

file_missing() {
  if [ ! $1 ];then
    print "$INFO_WARN" "File name is missing"
    echo "Usage: ${COLOR_GREEN}new -h$COLOR_RESET"
    exit 0
  fi
}

create_file() {
  TARGET_FILE=$TARGET_DIR/$1
  if [ ! -f $TARGET_FILE ];then
    printf "$2" >> $TARGET_FILE
    if [ $1 != 'README.md' ];then IS_DONE="true"; fi
    print "$INFO_OK" "$TARGET_FILE"
    if [ $1 == 'mod.rs' ];then
      echo "mod $DIR_NAME;" >> $ROOT_DIR/lib.rs
    fi
  else
    if [ $1 != 'README.md' ];then
      print "$INFO_EXISTS" "$TARGET_FILE"
    fi
  fi
}

create_file_type() {
  case $1 in
    js)
      FILE_CONTENTS="/*\n * @author: $AUTHOR\n * @create_at: $CREATE_AT\n */\n\nvar $NAME_2 = function() {\n  \n};"
    ;;
    rs)
      FILE_NAME="mod"
      FILE_CONTENTS="// @author: $AUTHOR\n// @create_at: $CREATE_AT\n\n#[allow(dead_code)]\npub fn $2() {\n  \n}\n\n#[test]\nfn test() {\n  \n}"
    ;;
    py)
      FILE_CONTENTS="# @author: $AUTHOR\n# @create_at: $CREATE_AT\n\ndef $NAME_2():\n  "
    ;;
    # TODO: more template
    *)
      break
    ;;
  esac

  create_file "$FILE_NAME.$1" "$FILE_CONTENTS"
}

print() {
  echo "$1$COLOR_RESET $2$COLOR_RESET"
}

camel_case() {
  str_arr=(`echo $1 | tr '_' ' '`)
  result=''
  for i in ${str_arr[@]}
  do
    first_letter=`echo ${i:0:1} | awk '{print toupper($0)}'`
    other_letter=${i:1}
    result=$result$first_letter$other_letter
  done

  if [ $2 == 'true' ];then
    first_result=$(echo ${result:0:1} | tr '[A-Z]' '[a-z]')
    result=$first_result${result:1}
  fi
  echo $result
  return $?
}

handle_args "$@"
main "$@"
